audio_diagnostics: print err when unable to dump CRAS
This allows simple grep in CrOS feedback system log
to know if CRAS dump fails

 - Remove "--dump_server_info" since it's the default arg
 - If "cras_test_client" fails print the error explicitly

BUG=b:245726082
TEST=stop cras; Verify audio_diagnostics

Change-Id: Id0b02834299375706362eba21a053b643345e7f4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/adhd/+/3882990
Tested-by: Hsinyu Chao <hychao@chromium.org>
Reviewed-by: Curtis Malainey <cujomalainey@chromium.org>
Reviewed-by: Yu-Hsuan Hsu <yuhsuan@chromium.org>
Commit-Queue: Hsinyu Chao <hychao@chromium.org>

diff --git a/scripts/audio_diagnostics b/scripts/audio_diagnostics
--- a/scripts/audio_diagnostics
+++ b/scripts/audio_diagnostics
@@ -29,8 +29,10 @@ in_the_list() {
     return 1
 }
 
+TAG="audio_diagnostics"
+
 echo '=== cras_test_client --dump_server_info ==='
-cras_test_client --dump_server_info
+cras_test_client || echo "${TAG}: Unable to dump CRAS info"
 
 echo '=== cras_test_client --dump_audio_thread ==='
 cras_test_client --dump_audio_thread
